CREATE TABLE customers (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salutation               VARCHAR(10)  NOT NULL,
    first_name               VARCHAR(100) NOT NULL,
    last_name                VARCHAR(100) NOT NULL,
    company_name             VARCHAR(200),
    email                    VARCHAR(255),
    phone                    VARCHAR(50),
    street                   VARCHAR(200) NOT NULL,
    postal_code              VARCHAR(10)  NOT NULL,
    city                     VARCHAR(100) NOT NULL,
    installation_street      VARCHAR(200),
    installation_postal_code VARCHAR(10),
    installation_city        VARCHAR(100),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customer_contacts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT        NOT NULL REFERENCES customers (id),
    contact_type VARCHAR(10)   NOT NULL,
    summary      VARCHAR(2000) NOT NULL,
    created_by   BIGINT        NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_customer_contacts_customer ON customer_contacts (customer_id);
