CREATE TABLE suppliers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL UNIQUE,
    email      VARCHAR(255),
    phone      VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Prices are net amounts in euros
CREATE TABLE products (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(50)    NOT NULL UNIQUE,
    name           VARCHAR(200)   NOT NULL,
    description    VARCHAR(1000),
    category       VARCHAR(20)    NOT NULL,
    unit           VARCHAR(10)    NOT NULL,
    purchase_price NUMERIC(10, 2) NOT NULL,
    selling_price  NUMERIC(10, 2) NOT NULL,
    supplier_id    BIGINT         NOT NULL REFERENCES suppliers (id),
    active         BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_supplier ON products (supplier_id);
