-- Counters for document numbers such as AN-2026-0001; one row per document type and year
CREATE TABLE document_sequences (
    name       VARCHAR(50) PRIMARY KEY,
    next_value BIGINT NOT NULL
);

-- Amounts are in euros; totals are stored so lists and reports do not have to recalculate them
CREATE TABLE quotes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_number     VARCHAR(20)    NOT NULL UNIQUE,
    customer_id      BIGINT         NOT NULL REFERENCES customers (id),
    status           VARCHAR(20)    NOT NULL,
    quote_date       DATE           NOT NULL,
    valid_until      DATE           NOT NULL,
    discount_percent NUMERIC(5, 2)  NOT NULL,
    vat_rate         NUMERIC(5, 2)  NOT NULL,
    net_total        NUMERIC(12, 2) NOT NULL,
    vat_amount       NUMERIC(12, 2) NOT NULL,
    gross_total      NUMERIC(12, 2) NOT NULL,
    notes            VARCHAR(2000),
    created_by       BIGINT         NOT NULL REFERENCES users (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_quotes_customer ON quotes (customer_id);

-- Article number, description, unit and price are copied from the product so later catalog changes do not alter the quote
CREATE TABLE quote_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id         BIGINT         NOT NULL REFERENCES quotes (id),
    product_id       BIGINT         NOT NULL REFERENCES products (id),
    line_number      INTEGER        NOT NULL,
    sku              VARCHAR(50)    NOT NULL,
    description      VARCHAR(200)   NOT NULL,
    unit             VARCHAR(10)    NOT NULL,
    quantity         NUMERIC(10, 2) NOT NULL,
    unit_price       NUMERIC(10, 2) NOT NULL,
    discount_percent NUMERIC(5, 2)  NOT NULL
);

CREATE INDEX idx_quote_items_quote ON quote_items (quote_id);
