-- An order is created from an accepted quote and takes its items and prices from that quote
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(20) NOT NULL UNIQUE,
    quote_id     BIGINT      NOT NULL UNIQUE REFERENCES quotes (id),
    status       VARCHAR(30) NOT NULL,
    order_date   DATE        NOT NULL,
    created_by   BIGINT      NOT NULL REFERENCES users (id),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
