-- Measurements, deliveries and installations for an order, each assigned to one employee
CREATE TABLE appointments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT      NOT NULL REFERENCES orders (id),
    appointment_type VARCHAR(20) NOT NULL,
    start_time       TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time         TIMESTAMP WITH TIME ZONE NOT NULL,
    assignee_id      BIGINT      NOT NULL REFERENCES users (id),
    notes            VARCHAR(1000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_appointments_start ON appointments (start_time);
CREATE INDEX idx_appointments_assignee ON appointments (assignee_id);
