-- What was ordered from which supplier for a customer order, and when it is due and arrived
CREATE TABLE supplier_orders (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number           VARCHAR(20)    NOT NULL UNIQUE,
    sales_order_id         BIGINT         NOT NULL REFERENCES orders (id),
    supplier_id            BIGINT         NOT NULL REFERENCES suppliers (id),
    status                 VARCHAR(20)    NOT NULL,
    ordered_date           DATE           NOT NULL,
    expected_delivery_date DATE           NOT NULL,
    actual_delivery_date   DATE,
    total                  NUMERIC(12, 2) NOT NULL,
    notes                  VARCHAR(1000),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Each supplier is ordered from once per customer order
    CONSTRAINT uq_supplier_orders_order_supplier UNIQUE (sales_order_id, supplier_id)
);

-- Article number, description, unit and purchase price are copied from the product at the time of ordering
CREATE TABLE supplier_order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_order_id BIGINT         NOT NULL REFERENCES supplier_orders (id),
    product_id        BIGINT         NOT NULL REFERENCES products (id),
    line_number       INTEGER        NOT NULL,
    sku               VARCHAR(50)    NOT NULL,
    description       VARCHAR(200)   NOT NULL,
    unit              VARCHAR(10)    NOT NULL,
    quantity          NUMERIC(10, 2) NOT NULL,
    purchase_price    NUMERIC(10, 2) NOT NULL
);

CREATE INDEX idx_supplier_order_items_order ON supplier_order_items (supplier_order_id);
