-- An invoice is a legal document: recipient and amounts are copied at issue and never change afterwards
CREATE TABLE invoices (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number        VARCHAR(20)    NOT NULL UNIQUE,
    sales_order_id        BIGINT         NOT NULL UNIQUE REFERENCES orders (id),
    status                VARCHAR(20)    NOT NULL,
    invoice_date          DATE           NOT NULL,
    -- Date the goods and services were delivered (Leistungsdatum), required on German invoices
    service_date          DATE           NOT NULL,
    due_date              DATE           NOT NULL,
    recipient_company     VARCHAR(200),
    recipient_name        VARCHAR(220)   NOT NULL,
    recipient_street      VARCHAR(200)   NOT NULL,
    recipient_postal_code VARCHAR(10)    NOT NULL,
    recipient_city        VARCHAR(100)   NOT NULL,
    vat_rate              NUMERIC(5, 2)  NOT NULL,
    net_total             NUMERIC(12, 2) NOT NULL,
    vat_amount            NUMERIC(12, 2) NOT NULL,
    gross_total           NUMERIC(12, 2) NOT NULL,
    -- Sum of the payments received so far
    paid_total            NUMERIC(12, 2) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_invoices_due_date ON invoices (due_date);

CREATE TABLE payments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT         NOT NULL REFERENCES invoices (id),
    amount     NUMERIC(12, 2) NOT NULL,
    paid_on    DATE           NOT NULL,
    note       VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payments_invoice ON payments (invoice_id);
