-- Who changed which record, and when. Holds the names of changed fields but never their values,
-- so the log itself contains no personal data. user_id is deliberately not a foreign key: a log entry
-- must survive whatever later happens to the user record. Null means the system itself (e.g. demo data).
CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id        BIGINT,
    action         VARCHAR(20)  NOT NULL,
    entity_type    VARCHAR(50)  NOT NULL,
    entity_id      BIGINT       NOT NULL,
    changed_fields VARCHAR(1000)
);

CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);

-- Set when a customer's personal data was erased on request while their business documents had to be kept
ALTER TABLE customers ADD COLUMN anonymized_at TIMESTAMP WITH TIME ZONE;
